name: Deploy to Elastic Beanstalk
on:
  push:
    branches: [main]
jobs:
  build:
    permissions:
      contents: write
      id-token: write
  # deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Configure AWS credentials
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
      #   run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_DEFAULT_REGION
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730755949664:role/gitactions
          role-session-name: gitactions
          aws-region: us-east-1
      - name: Install EB CLI
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python3 -m venv ebcli
          source ebcli/bin/activate
          pip3 install awscli --upgrade
          pip3 install awsebcli --upgrade
      - name: Deploy to Elastic Beanstalk
        run: |
          cp package.json ./dist/
          cd dist
          eb init --region us-east-1 --platform "Node.js 20 running on 64bit Amazon Linux 2023" collabdash
          eb deploy backend-collabdash
          eb deploy fwddigi-collabdash
          eb deploy eifgeosolutions-collabdash
          eb deploy apexsolutions-collabdash
          eb deploy demo-collabdash
