name: Deploy to Elastic Beanstalk
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_DEFAULT_REGION
      - name: Install AWS CLI and EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y
          sudo apt-get install python3-pip
          pip3 install --user --upgrade awsebcli
      - name: Deploy to Elastic Beanstalk
        run: |
          cp package.json ./dist/
          cd dist
          eb init --region us-east-1 --platform "Node.js 20 running on 64bit Amazon Linux 2023" collabdash
          eb deploy backend-collabdash
          eb deploy fwddigi-collabdash
          eb deploy eifgeosolutions-collabdash
          eb deploy apexsolutions-collabdash
          eb deploy demo-collabdash
